name: Backup Turso Database

on:
  schedule:            # <-- Lỗi thụt đầu dòng ở đây
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Install Turso CLI
        run: |
          DOWNLOAD_URL="https://github.com/tursodatabase/turso-cli/releases/download/v1.0.11/turso-cli_Linux_x86_64.tar.gz"
          curl -L -o turso.tar.gz "$DOWNLOAD_URL"
          tar -xzf turso.tar.gz
          sudo mv turso /usr/local/bin/
          turso --version
      - name: Backup Database
        id: create_backup_file
        run: |
          export PATH="/usr/local/bin:${PATH}"
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M")
          FILENAME="backup-${TIMESTAMP}.sql.gz"
          turso db shell policytrack .dump | gzip > $FILENAME
          echo "filename=$FILENAME" >> $GITHUB_OUTPUT
        env:
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}

      - name: Install pip
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
      - name: Install AWS CLI
        run: |
          python3 -m pip install --upgrade pip
          pip install awscli
          aws --version
      - name: Upload backup to R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
        run: |
          aws s3 cp ${{ steps.create_backup_file.outputs.filename }} s3://${{ secrets.R2_BUCKET_NAME }}/ --endpoint-url ${{ secrets.R2_ENDPOINT_URL }}
